describe('Basic page interactions', () => {
    beforeEach(() => {
        cy.visit('/example-4')
    })
    it('Should set the header text to the item\'s name when double clicked', () => {
        cy.get('[data-cy="box-1-selected-name"]')
            .invoke('text')
            .should('eq', 'Nothing selected')
        cy.get('[data-cy="box-1-items-list"] > :nth-child(1)')
            .dblclick()
        cy.get('[data-cy="box-1-selected-name"]')
            .invoke('text')
            .should('eq', 'Option One')
        cy.get('[data-cy="box-1-items-list"] > :nth-child(2)')
            .dblclick()
        cy.get('[data-cy="box-1-selected-name"]')
            .invoke('text')
            .should('eq', 'Option Two')
        cy.get('[data-cy="box-1-items-list"] > :nth-child(3)')
            .dblclick()
        cy.get('[data-cy="box-1-selected-name"]')
            .invoke('text')
            .should('eq', 'Option Three')
    })
    it('Should display a correct count for the number of selected checkboxes', () => {
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '0')
        cy.get('[data-cy="box-2-checkboxes"] > :nth-child(1) > input')
            .check()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '1')
        cy.get('[data-cy="box-2-checkboxes"] > :nth-child(2) > input')
            .check()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '2')
        cy.get('[data-cy="box-2-checkboxes"] > :nth-child(3) > input')
            .check()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '3')
        cy.get('[data-cy="box-2-checkboxes"] > :nth-child(1) > input')
            .uncheck()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '2')
        cy.get('[data-cy="box-2-checkboxes"] > :nth-child(2) > input')
            .uncheck()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '1')
            cy.get('[data-cy="box-2-checkboxes"] > :nth-child(3) > input')
            .uncheck()
        cy.get('[data-cy="box-2-selected-count"]')
            .invoke('text')
            .should('eq', '0')
    })
    it('Should display the name of the currently selected item', () => {
        cy.get('[data-cy="box-3-selected-name"]')
            .invoke('text')
            .should('eq', 'Nothing selected')
        cy.get('[data-cy="box-3-dropdown"]')
            .select(1) // 'Option One' doesn't work as a first choice because it's selected as default option
        cy.get('[data-cy="box-3-selected-name"]')
            .invoke('text')
            .should('eq', 'Option Two')
        cy.get('[data-cy="box-3-dropdown"]')
            .select(0) 
        cy.get('[data-cy="box-3-selected-name"]')
            .invoke('text')
            .should('eq', 'Option One')
        cy.get('[data-cy="box-3-dropdown"]')
            .select(2) 
        cy.get('[data-cy="box-3-selected-name"]')
            .invoke('text')
            .should('eq', 'Option Three')
    })
})
